dataSource:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/clevertec_task
  username: postgres
  password: root
pagination:
  pageSize: 20
  pageNumber: 1
cache:
  type: LRU
  capacity: 10